import { css } from '@emotion/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { useRecoilValue } from 'recoil'
import CompponentPokemon from '@/components/Pokemon'
import { getPokemons } from '@/lib/pokemon'
import { generationState } from '@/state/selectGeneration'
import styles from '@/styles/Home.module.css'
import { Pokemon } from '@/types/typeList'

const itemsStyle = css`
  display: flex;
  flex-wrap: wrap;
  margin-top: 30px;
`

const Zukan: NextPage = () => {
  const [pokemonList, setPokemonList] = useState(Array<Pokemon>)
  const [generation, setGen] = useRecoilValue(generationState)

  useEffect(() => {
    const loadPokemon = async () => {
      const pokemons = await getPokemons()
      setPokemonList(pokemons)
    }
    loadPokemon()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>POKEMON ZUKAN</h1>
        <div className='items' css={itemsStyle}>
          {pokemonList.map((item) => (
            <CompponentPokemon poke={item} key={item.id} />
          ))}
        </div>
      </main>
    </div>
  )
}

export default Zukan
